NAME: libftprintf.a

HEADER: printf.h

CFLAGS = -Wall -Wextra -Werror

SRC = ft_printf.c ft_printf_utils.c

all: $(NAME)

$(NAME): $(SRC:.c=.o)
	ar rc $(NAME) $(SRC:.c=.o)
	ranlib $(NAME)

$(obj)*.o: *.c
	gcc $(CFLAGS) -include $(HEADER) -c $< -o $@

clean: $(RM) $(SRC:.c=.o)

fclean: clean
	$(RM) $(NAME)

re: fclean all

norm: norminette -R CheckForbiddenSourceHeader *.c

.PHONY: all clean fclean re
